---
title: "Forecasting Influenza from New York"
output: html_notebook
---

Forecasting Ne using BNPR

```{r}
library(phylodyn)
library(dplyr)
library(ggplot2)
library(PILAF)

H3N2_tree <- ape::read.nexus(system.file("extdata/H3N2/MCC.tree",
                                         package = "PILAF"))
plot(ape::ladderize(H3N2_tree),show.tip.label=FALSE)
H3N2_last_time <- 2019.0739726027398
ar2crw1_formula <- y ~ -1 + f(time, model = "ar", order = 2) +
      f(week, model = "rw1", cyclic = T, constr = F)
H3N2_Ne_forecast <- BNPR_forecast(H3N2_tree, last_time = H3N2_last_time, formula = ar2crw1_formula, pred = 20)
BNPR <- BNPR(H3N2_tree)
```

The next figure compares estimation with the AR(2)+CRW(1) (black curve) to BNPR (red curve)
```{r}
p_ar2crw1_data <- with(H3N2_Ne_forecast, data.frame(time = H3N2_last_time - result$summary.random$time$ID,
                                  mean = effpopmean, 
                                  lwr = effpop025,
                                  upr = effpop975))
BNPR_data <- with(BNPR, data.frame(time = H3N2_last_time - result$summary.random$time$ID,
                                  mean = effpopmean, 
                                  lwr = effpop025,
                                  upr = effpop975)) 
  
xmin <- c()
xmax <- c()
year <- floor(min(p_ar2crw1_data$time))
while (year < max(p_ar2crw1_data$time)) {
  xmin <- c(xmin, year + 0.9)
  xmax <- c(xmax, year + 1.2)
  year = year + 1
}
winter_seasons <- data.frame(xmin = xmin, xmax = xmax) %>%
  filter(xmin < max(p_ar2crw1_data$time) & xmax > min(p_ar2crw1_data$time))

p_ar2crw1 <- ggplot() +
  geom_rect(data = winter_seasons, aes(xmin = xmin, xmax = xmax, ymin = min(p_ar2crw1_data$lwr), ymax = max(p_ar2crw1_data$upr)), fill = 'steelblue', alpha = 0.1) +
  geom_ribbon(data = p_ar2crw1_data, aes(x = time, ymin = lwr, ymax = upr), fill = 'gray', alpha = 0.3) +
  geom_line(data = p_ar2crw1_data, aes(x = time, y = mean)) +
  theme_classic() +
  scale_y_log10() +
  geom_vline(aes(xintercept = H3N2_last_time - H3N2_Ne_forecast$result$summary.random$time$ID[21]), linetype = 'dotdash') +
  ylab('Ne') + 
  geom_line(data = BNPR_data, aes(x = time, y = mean), col = "red") 
p_ar2crw1
```

This will be the same as above but we will truncate our tree 
```{r}
H3N2_tree <- ape::read.nexus(system.file("extdata/H3N2/MCC.tree",
                                         package = "PILAF"))
H3N2_last_time <- 2019.0739726027398

truncation_time<-.08 #about 4 weeks
H3N2_truncated<-truncate_data(H3N2_tree,truncation_time)
H3N2_Ne_forecast <- BNPR_forecast(H3N2_truncated, last_time = H3N2_last_time-truncation_time, formula = ar2crw1_formula, pred = 20)

p_ar2crw1_data <- with(H3N2_Ne_forecast, data.frame(time = H3N2_last_time-truncation_time - result$summary.random$time$ID,
                                  mean = effpopmean, 
                                  lwr = effpop025,
                                  upr = effpop975))
xmin <- c()
xmax <- c()
year <- floor(min(p_ar2crw1_data$time))
while (year < max(p_ar2crw1_data$time)) {
  xmin <- c(xmin, year + 0.9)
  xmax <- c(xmax, year + 1.2)
  year = year + 1
}
winter_seasons <- data.frame(xmin = xmin, xmax = xmax) %>%
  filter(xmin < max(p_ar2crw1_data$time) & xmax > min(p_ar2crw1_data$time))

p_ar2crw1 <- ggplot() +
  geom_rect(data = winter_seasons, aes(xmin = xmin, xmax = xmax, ymin = min(p_ar2crw1_data$lwr), ymax = max(p_ar2crw1_data$upr)), fill = 'steelblue', alpha = 0.1) +
  geom_ribbon(data = p_ar2crw1_data, aes(x = time, ymin = lwr, ymax = upr), fill = 'gray', alpha = 0.3) +
  geom_line(data = p_ar2crw1_data, aes(x = time, y = mean)) +
  theme_classic() +
  scale_y_log10() +
  geom_vline(aes(xintercept = H3N2_last_time-truncation_time - H3N2_Ne_forecast$result$summary.random$time$ID[21]), linetype = 'dotdash') +
  ylab('Ne') + 
  geom_line(data = BNPR_data, aes(x = time, y = mean), col = "red") 
p_ar2crw1
```

# BNPR PS forecast

```{r}
H3N2_tree <- ape::read.nexus(system.file("extdata/H3N2/MCC.tree",
                                         package = "PILAF"))
H3N2_last_time <- 2019.0739726027398
truncation_time <- 0.08 # about 4 weeks
# BNPR_PS_formula <- Y ~ -1 + beta0 +
#         f(time, model="rw1", hyper = hyper, constr = FALSE) +
#         f(time2, w, copy="time", fixed=FALSE, param=c(0, beta1_prec))
BNPR_PS_formula <- Y ~ -1 + beta0 +
        f(time, model="ar", order = 2, constr = FALSE) +
        f(time2, w, copy="time", fixed=FALSE) +
  f(week, model = "rw1", cyclic = T) +
  f(week2, w, copy = "week", fixed = F)
H3N2_truncated <- truncate_data(H3N2_tree, truncation_time)
H3N2_Ne_forecast <- BNPR_forecast(H3N2_truncated, last_time = H3N2_last_time - truncation_time, formula = BNPR_PS_formula, pred = 4, pref = T)

# plot the forecast
H3N2_MCC_phylo <- phylodyn::summarize_phylo(H3N2_tree)
H3N2_root_time <- H3N2_last_time - max(H3N2_MCC_phylo$coal_times)
H3N2_PS_df <- BNPR_to_df(H3N2_Ne_forecast, label = "H3N2 BNPR PS", H3N2_last_time - truncation_time)
plot_trajectory(H3N2_PS_df, c(min(H3N2_PS_df$Lower), max(H3N2_PS_df$Upper)), seq(2014, 2019), H3N2_root_time, vline = H3N2_last_time - truncation_time - H3N2_Ne_forecast$result$summary.random$time$ID[4])
```

```{r}
rw1_formula <- y ~ -1 + f(time, model = "rw1", constr = F) 
rw1_H3N2_Ne_forecast <- BNPR_forecast(H3N2_tree, last_time = H3N2_last_time, formula = ar2crw1_formula, pred = 20)
``` 

```{r}
p_rw1_data <- with(rw1_H3N2_Ne_forecast, data.frame(time = H3N2_last_time - result$summary.random$time$ID,
                                  mean = effpopmean, 
                                  lwr = effpop025,
                                  upr = effpop975)) 

xmin <- c()
xmax <- c()
year <- floor(min(p_rw1_data$time))
while (year < max(p_rw1_data$time)) {
  xmin <- c(xmin, year + 0.9)
  xmax <- c(xmax, year + 1.2)
  year = year + 1
}
winter_seasons <- data.frame(xmin = xmin, xmax = xmax) %>%
  filter(xmin < max(p_rw1_data$time) & xmax > min(p_rw1_data$time))

p_rw1 <-  ggplot() +
  geom_rect(data = winter_seasons, aes(xmin = xmin, xmax = xmax, ymin = min(p_rw1_data$lwr), ymax = max(p_rw1_data$upr)), fill = 'steelblue', alpha = 0.1) +
  geom_ribbon(data = p_rw1_data, aes(x = time, ymin = lwr, ymax = upr), fill = 'gray', alpha = 0.3) +
  geom_line(data = p_rw1_data, aes(x = time, y = mean)) +
  theme_classic() +
  scale_y_log10() +
  ylab('Ne') + 
  geom_vline(aes(xintercept = H3N2_last_time - H3N2_Ne_forecast$result$summary.random$time$ID[21]), linetype = 'dotdash') +
  geom_line(data = BNPR_data, aes(x = time, y = mean), col = "red")  
p_rw1
```

```{r}
library(cowplot)
p_all <- cowplot::plot_grid(
  cowplot::plot_grid(ggdraw() + draw_label('RW(1)'), p_rw1, ncol = 1, rel_heights = c(0.1, 1)), 
  cowplot::plot_grid(ggdraw() + draw_label('AR(2) + cRW(1)'), p_ar2crw1 + theme(axis.title.y = element_blank()),  rel_heights = c(0.1, 1), ncol = 1), 
  ncol = 2)
p_all
#ggsave(p_all, file = '../../projectingvirus/manuscript/Figures/Ne/forecast_Ne.pdf', width = 6, height = 3)
```
