---
title: "CDC ILI forecast"
output: 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We used New York State ILI counts as an example to demonstrate phylodynamics forecasting. To obtain latest data from CDC, we install the `cdcfluview` package:

```r
devtools::install_github("hrbrmstr/cdcfluview")
```

We first visualized the total ILI counts for each flu season (week 40 - week 21). 

```{r}
library(cdcfluview)
library(dplyr)
library(ggplot2)
library(phylodyn)

NY_ILI <- ilinet("state") %>%
  filter(region == "New York") %>%
  select("year", "week", "ilitotal", "week_start") 

p_ILI <- visualize_flu_season(NY_ILI, "ilitotal")
p_ILI
```

We can also visualize the inferred trajectory. 

```{r}
H3N2_tree <- ape::read.nexus(system.file("extdata/H3N2/MCC.tree",
                                         package = "PILAF"))
H3N2_last_time <- 2019.0739726027398
ar2crw1_formula <- y ~ -1 + f(time, model = "ar", order = 2) +
      f(week, model = "rw1", cyclic = T, constr = F)
H3N2_Ne_forecast <- BNPR_forecast(H3N2_tree, last_time = H3N2_last_time, formula = ar2crw1_formula, pred = 0)
Ne_data <- with(H3N2_Ne_forecast, data.frame(time = H3N2_last_time - result$summary.random$time$ID,
                                             week = weeks,
                                             Ne = effpopmean))
Ne_data$year <- floor(Ne_data$time)
p_Ne <- visualize_flu_season(Ne_data, "Ne")
p_Ne
```

```{r}
cowplot::plot_grid(p_ILI, p_Ne)
```

We can also explore individual seasons. 

```{r}
subset_seasons <- c("2014-2015", "2015-2016")
cowplot::plot_grid(plotlist = purrr::imap(list(ilitotal = NY_ILI, Ne = Ne_data), 
                               ~ visualize_flu_season(.x, .y, subset_season = subset_seasons)))
```
